# -*- coding: utf-8 -*-
"""ReAct Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BCW1Dc2w0ogrcUMLuhz8d3fBb9YuLPAe
"""

!pip install requests python-dotenv -q

import os

os.environ["MISTRAL_API_KEY"] = "9YHjvYnt3uEJ5riSS4p5Lr8SduY5TwL8"

print(os.getenv("MISTRAL_API_KEY"))

from IPython.core import payload
import requests
import json

API_KEY = os.getenv("MISTRAL_API_KEY")
BASE_URL = "https://api.mistral.ai/v1/chat/completions"

def call_mistral(prompt , model = 'mistral-small-latest'):
  headers = {
      "Content-Type": "application/json",
      "Authorization": f"Bearer {API_KEY}"
  }

  payload = {
      "model":model,
      "messages": [
          {"role":"system", "content": "You are a hepful reasoning agent."},
          {"role":"user", "content": prompt}
      ]
  }

  response = requests.post(BASE_URL, json=payload, headers=headers)

  if response.status_code != 200:
    raise Exception(f"Request failed with status code {response.status_code}")

  return response.json()['choices'][0]['message']['content']

def search_tool(query):
    return f"[Search Result for '{query}']: Example placeholder result."

def calculator_tool(expression):
   try:
        return str(eval(expression))
   except:
        return "Error: Invalid math expression"

import re

def react_agent(query, max_steps=5):
    history = f"User query: {query}\n\n"

    for step in range(max_steps):
        prompt = history + "Thought:"

        llm_output = call_mistral(prompt)

        history += f"Thought: {llm_output}\n"

        # Detect an action
        action_match = re.search(r"Action: (\w+)\[(.*?)\]", llm_output)

        if not action_match:
            return llm_output  # No action → final answer

        action_name = action_match.group(1)
        action_input = action_match.group(2)

        # Handle tools
        if action_name.lower() == "search":
            observation = search_tool(action_input)
        elif action_name.lower() == "calculator":
            observation = calculator_tool(action_input)
        else:
            observation = "Unknown tool."

        # Add observation back to history
        history += f"Observation: {observation}\n"

        # Let model use the observation
        history += "Response: "

    return "Max steps reached."

